#!/bin/sh
# This file can be used by supervisor to run command in the virtual env
# Simply copy it to an accissible place
. bqenv/bin/activate
mkdir -p /tmp/bisque-python-eggs
export PYTHON_EGG_CACHE=/tmp/bisque-python-eggs
PATH=.:$PATH

IP_ADDRESS=$(resolve-container-ip || hostname --ip-address)
export IP_ADDRESS

echo "STARTING " $(date)
exec $@
