#!/bin/sh
#  This script is run in a clean environment (NO PATH, etc) on the remote
#  node.   All needed ENV vars must be set up before launching the script.
#
#
matlabroot=/cluster/home/matlab
LD_LIBRARY_PATH=$matlabroot/runtime/glnxa64:\
$matlabroot/bin/glnxa64:\
$matlabroot/sys/os/glnxa64:\
$matlabroot/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:\
$matlabroot/sys/java/jre/glnxa64/jre/lib/amd64/server:\
$matlabroot/sys/java/jre/glnxa64/jre/lib/amd64:
XAPPLRESDIR=$matlabroot/X11/app-defaults 

PATH=$PATH:/cluster/home/matlab/bin:.
HOME=.
DISPLAY=:0.0

export PATH LD_LIBRARY_PATH HOME DISPLAY  XAPPLRESDIR

SCRIPT=$1; shift;

echo "+++NODE"
hostname

echo "+++LOCAL DIR"
pwd
ls -l 

echo "+++ENVIRONMENT"
printenv


echo "+++EXEC of ./$SCRIPT and $@"
exec ./$SCRIPT $@
