apiVersion: v1
kind: Secret
metadata:
  name: bisque-secret
  namespace: bisque
type: Opaque
stringData:
  BISQUE_SECRET: change-me
  BISQUE_DBURL: postgresql://bisque:bisque@postgres:5432/bisque
  BISQUE_SMTP_PASSWORD: ""
  POSTGRES_DB: bisque
  POSTGRES_USER: bisque
  POSTGRES_PASSWORD: bisque
