#!/usr/bin/python

""" Image service testing framework
update config to your system: config.cfg
call by: python run_tests.py
"""

__module__    = "run_tests"
__author__    = "Dmitry Fedorov"
__version__   = "1.0"
__revision__  = "$Rev$"
__date__      = "$Date$"
__copyright__ = "Center for BioImage Informatics, University California, Santa Barbara"

import sys
if sys.version_info  < ( 2, 7 ):
    import unittest2 as unittest
else:
    import unittest
import os
import posixpath
import urlparse
import time
from lxml import etree
import ConfigParser
from bqapi import BQSession, BQCommError
from bqapi.util import save_blob, localpath2url

##################################################################
# Upload
##################################################################


config = ConfigParser.ConfigParser()
config.read('config.cfg')

root = config.get('Host', 'root') or 'localhost:8080'
user = config.get('Host', 'user') or 'test'
pswd = config.get('Host', 'password') or 'test'

session = BQSession().init_local(user, pswd,  bisque_root=root, create_mex=False)

request = '<image name="%s">'%'NHE-RF-p1.lei'
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1.lei'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z000_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z000_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z001_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z001_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z002_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z002_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z003_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z003_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z004_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z004_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z005_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z005_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z006_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z006_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z007_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z007_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z008_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z008_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z009_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z009_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z010_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z010_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z011_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z011_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z012_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z012_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z013_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z013_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z014_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z014_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z015_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z015_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z016_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z016_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z017_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z017_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z018_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z018_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z019_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z019_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z020_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z020_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z021_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z021_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z022_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z022_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z023_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z023_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z024_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z024_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z025_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z025_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z026_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z026_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z027_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series02_z027_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z000_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z000_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z001_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z001_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z002_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z002_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z003_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z003_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z004_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z004_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z005_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z005_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z006_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z006_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z007_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z007_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z008_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z008_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z009_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z009_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z010_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z010_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z011_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z011_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z012_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z012_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z013_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z013_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z014_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z014_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z015_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z015_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z016_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z016_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z017_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z017_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z018_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z018_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z019_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z019_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z020_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z020_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z021_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z021_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z022_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z022_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z023_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z023_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z024_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z024_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z025_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z025_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z026_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z026_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z027_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series04_z027_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z000_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z000_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z001_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z001_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z002_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z002_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z003_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z003_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z004_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z004_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z005_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z005_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z006_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z006_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z007_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z007_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z008_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z008_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z009_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z009_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z010_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z010_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z011_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z011_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z012_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z012_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z013_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z013_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z014_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z014_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z015_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z015_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z016_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z016_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z017_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z017_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z018_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z018_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z019_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z019_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z020_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z020_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z021_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z021_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z022_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z022_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z023_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z023_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z024_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z024_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z025_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z025_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z026_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series06_z026_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z000_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z000_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z001_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z001_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z002_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z002_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z003_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z003_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z004_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z004_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z005_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z005_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z006_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z006_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z007_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z007_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z008_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z008_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z009_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z009_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z010_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z010_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z011_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z011_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z012_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z012_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z013_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z013_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z014_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z014_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z015_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z015_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z016_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z016_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z017_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z017_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z018_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z018_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z019_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z019_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z020_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z020_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z021_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z021_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z022_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z022_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z023_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z023_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z024_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z024_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z025_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z025_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z026_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z026_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z027_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z027_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z028_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series08_z028_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z000_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z000_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z001_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z001_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z002_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z002_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z003_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z003_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z004_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z004_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z005_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z005_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z006_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z006_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z007_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z007_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z008_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z008_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z009_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z009_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z010_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z010_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z011_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z011_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z012_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z012_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z013_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z013_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z014_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z014_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z015_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z015_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z016_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z016_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z017_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z017_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z018_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z018_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z019_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z019_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z020_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z020_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z021_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z021_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z022_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z022_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z023_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z023_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z024_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z024_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z025_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z025_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z026_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z026_ch01.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z027_ch00.tif'))
request = '%s<value>%s</value>'%(request, localpath2url('f:/dima/develop/python/bq5irods/data/imagedir/admin/tests/multi_file/NHE-RF-p1/NHE-RF-p1_Series11_z027_ch01.tif'))
request = '%s</image>'%request

#url = session.service_url('data_service', 'image')
#r = session.postxml(url, etree.fromstring(request), method='POST')
r = save_blob(session, resource=request)
if r is None or r.get('uri') is None:
    print 'Upload failed'
else:
    print 'id: %s'%r.get('resource_uniq')
    print 'url: %s'%r.get('uri')
