#!/usr/bin/env python3
"""Generate BisQue runtime config from the public BISQUE_* environment."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import uuid
from pathlib import Path
from urllib.parse import urlparse

GENERATED = (
    "# Generated by scripts/generate-config.py. Do not edit by hand.\n"
    "# Edit .env or exported BISQUE_* variables, then run just setup."
)


def env(name: str, default: str) -> str:
    value = os.environ.get(name)
    return value if value not in (None, "") else default


def as_bool(value: str, default: bool = False) -> bool:
    if value == "":
        return default
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on", "y"}:
        return True
    if normalized in {"0", "false", "no", "off", "n"}:
        return False
    raise SystemExit(f"Expected boolean value, got {value!r}")


def validate_dburl(dburl: str) -> str:
    parsed = urlparse(dburl)
    if not parsed.scheme:
        raise SystemExit(f"BISQUE_DBURL must include a scheme: {dburl!r}")
    if parsed.scheme == "sqlite" and not dburl.startswith("sqlite:///"):
        raise SystemExit("sqlite BISQUE_DBURL must use sqlite:///path/to/db")
    return dburl


def resolve_path_list(value: str, base: Path) -> str:
    paths = []
    for item in value.split(","):
        item = item.strip()
        if not item:
            continue
        path = Path(item).expanduser()
        if not path.is_absolute():
            path = base / path
        paths.append(path.resolve().as_posix())
    return ",".join(paths)


def read_existing_value(path: Path, key: str) -> str | None:
    if not path.exists():
        return None
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=\s*(.*)\s*$")
    for line in path.read_text(errors="ignore").splitlines():
        match = pattern.match(line)
        if match:
            return match.group(1).strip()
    return None


def backup_if_changed(path: Path, content: str) -> None:
    if not path.exists():
        return
    old = path.read_text(errors="ignore")
    if old == content:
        return
    backup = path.with_suffix(path.suffix + ".bak")
    counter = 1
    while backup.exists():
        backup = path.with_suffix(path.suffix + f".bak{counter}")
        counter += 1
    shutil.copy2(path, backup)


def write_generated(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    backup_if_changed(path, content)
    path.write_text(content)


def copy_default(defaults_dir: Path, name: str, target: Path) -> None:
    source = defaults_dir / f"{name}.default"
    if not source.exists():
        return
    if target.exists():
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, target)


def set_section_value(path: Path, section: str, key: str, value: str) -> None:
    lines = path.read_text(errors="ignore").splitlines()
    in_section = False
    section_seen = False
    updated = False
    output: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            if in_section and not updated:
                output.append(f"{key} = {value}")
                updated = True
            in_section = stripped == f"[{section}]"
            section_seen = section_seen or in_section
        if in_section and stripped.startswith(f"{key}"):
            output.append(f"{key} = {value}")
            updated = True
            continue
        output.append(line)

    if section_seen and in_section and not updated:
        output.append(f"{key} = {value}")
    elif not section_seen:
        output.extend(["", f"[{section}]", f"{key} = {value}"])

    path.write_text("\n".join(output) + "\n")


def make_site_cfg(values: dict[str, str]) -> str:
    return f"""{GENERATED}

[servers]
backend = paster
servers = h1
log_dir = {values["log_dir"]}
pid_dir = {values["run_dir"]}
h1.url = {values["public_url"]}
h1.services_enabled = {values["services_enabled"]}
h1.services_disabled = {values["services_disabled"]}
h1.bisque.static_files = true

[app:main]
use = egg:bqcore
make_body_seekable = true
full_stack = true

bisque.organization = {values["organization"]}
bisque.title = {values["title"]}
bisque.admin_email = {values["admin_email"]}
bisque.admin_id = admin
bisque.welcome_message = Welcome to the Bisque database
bisque.js_environment = {values["js_environment"]}

bisque.server = {values["public_url"]}
bisque.services_enabled = {values["services_enabled"]}
bisque.services_disabled = {values["services_disabled"]}
bisque.installed = finished
bisque.paths.root = {values["source_dir"]}
bisque.paths.data = {values["data_dir"]}
bisque.paths.config = {values["config_dir"]}
bisque.paths.share = {values["source_dir"]}
bisque.paths.run = {values["runtime_dir"]}
bisque.paths.public = {values["public_dir"]}
bisque.paths.depot = {values["external_dir"]}
bisque.paths.virtualenv = {values["venv"]}
bisque.paths.default = {values["defaults_dir"]}
bisque.paths.bin = {values["venv"]}/bin
bisque.paths.packages = {values["packages_dir"]}
bisque.paths.jslocation = bqcore
bisque.paths.reports = {values["reports_dir"]}
bisque.paths.staging = {values["staging_dir"]}
bisque.paths.modules = ./modules
bisque.paths.plugins = ./plugins

bisque.blob_service.subtransaction = true
bisque.blob_service.stores = local
bisque.blob_service.cache_max_age = 3628800
bisque.stores.local.mounturl = file://$datadir/imagedir/$user/
bisque.stores.local.top = file://$datadir/imagedir/

bisque.engine_service.module_dirs = {values["module_dirs"]}
bisque.image_service.imgcnv.omp_num_threads = 4
bisque.image_service.cache_max_age = 3628800
bisque.import_service.upload_dir = {values["upload_dir"]}

bisque.login.timeout = 60
bisque.login.session_length = 60480
bisque.login.password = hashed
bisque.login.providers = local
bisque.login.local.text = Local Login
bisque.login.local.url = /auth_service/login
bisque.login.local.icon = /core/images/signin/signin_bisque.png
bisque.login.local.type = internal

runtime.staging_base = {values["staging_dir"]}
runtime.matlab_home =
runtime.platforms = command

docker.enabled = True
docker.backend = {values["docker_backend"]}
docker.hub = {values["docker_hub"]}
docker.hub.user =
docker.callback_url = {values["docker_callback_url"]}
docker.login_tmpl =
docker.argo.workflow_template = {values["docker_argo_workflow_template"]}
docker.argo.gpu_workflow_template = {values["docker_argo_gpu_workflow_template"]}

beaker.session.key = bq
beaker.session.secret = {values["secret"]}
beaker.cache.type = file
beaker.cache.data_dir = {values["data_dir"]}/beakercache
beaker.cache.lock_dir = {values["data_dir"]}/beakerlock

bisque.smtp.host = {values["smtp_host"]}
bisque.smtp.port = {values["smtp_port"]}
bisque.smtp.username = {values["smtp_user"]}
bisque.smtp.password = {values["smtp_password"]}
bisque.smtp.tls = {values["smtp_tls"]}
bisque.smtp.ssl = {values["smtp_ssl"]}
bisque.smtp.timeout = {values["smtp_timeout"]}
bisque.mail.from_email = {values["mail_from"]}
bisque.mail.from_name = {values["mail_from_name"]}
bisque.registration.email_verification.enabled = {values["email_verification"]}

sqlalchemy.url = {values["dburl"]}
sqlalchemy.echo = false
sqlalchemy.echo_pool = false
sqlalchemy.pool_recycle = 3600
sqlalchemy.pool_pre_ping = true

who.config_file = %(here)s/who.ini
who.log_level = error
who.log_stream = auth

set debug = {values["debug"]}
templating.mako.reloadfromdisk = true
templating.mako.compiled_templates_dir = {values["data_dir"]}/templates
toscawidgets.framework.resource_variant = debug

[loggers]
keys = root, bqapi, bq, locks, sqlalchemy, auth

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = ERROR
handlers = console

[logger_bqapi]
level = WARN
handlers =
qualname = bqapi

[logger_bq]
level = INFO
handlers =
qualname = bq

[logger_locks]
level = INFO
handlers =
qualname = bq.util.locks

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_auth]
level = WARN
handlers =
qualname = auth

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s,%(msecs)03d %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""


def make_runtime_cfg(values: dict[str, str]) -> str:
    return f"""{GENERATED}
runtime.platforms = command
runtime.staging_base = {values["staging_dir"]}
runtime.matlab_home =
runtime.matlab_launcher = config-defaults/templates/matlab_launcher_SYS.tmpl
bisque.server = {values["public_url"]}

[docker]
docker.enabled = True
docker.backend = {values["docker_backend"]}
docker.hub = {values["docker_hub"]}
docker.hub.user =
docker.hub.password =
docker.hub.email =
docker.callback_url = {values["docker_callback_url"]}
docker.login_tmpl =
docker.argo.workflow_template = {values["docker_argo_workflow_template"]}
docker.argo.gpu_workflow_template = {values["docker_argo_gpu_workflow_template"]}
docker.image.matlab_runtime = biodev.ece.ucsb.edu:5000/mcr_runtime_2015b
docker.image.dream3d = biodev.ece.ucsb.edu:5000/dream3d
docker.image.cellprofiler = biodev.ece.ucsb.edu:5000/cellprofiler
"""


def make_paster_cfg(values: dict[str, str]) -> str:
    return f"""{GENERATED}

[DEFAULT]

[server:main]
use = egg:Paste#http
host = {values["http_host"]}
port = {values["http_port"]}
protocol_version = HTTP/1.1

[sa_auth]
cookie_secret = {values["secret"]}

[app:main]
use = config:site.cfg
bisque.server = {values["public_url"]}
bisque.services_enabled = {values["services_enabled"]}
bisque.services_disabled = {values["services_disabled"]}
bisque.static_files = true
"""


def make_test_cfg(values: dict[str, str]) -> str:
    return f"""{GENERATED}

[DEFAULT]

[server:main]
use = egg:Paste#http
host = localhost
port = {values["http_port"]}

[app:main]
use = config:site.cfg
sqlalchemy.url = {values["dburl"]}
skip_authentication = true

[app:main_with_auth]
use = config:site.cfg
sqlalchemy.url = {values["dburl"]}
skip_authentication = false

[test]
host.root = http://127.0.0.1:{values["http_port"]}
host.user = admin
host.password = admin

[store]
samples_url = {values["fixture_dir"]}
input_dir = {values["fixture_dir"]}
results_dir = {values["data_dir"]}/test-results
files = flowers_24bit_nointr.png
"""


def make_alembic_cfg(defaults_dir: Path, values: dict[str, str]) -> str:
    source = defaults_dir / "alembic.ini.default"
    if source.exists():
        text = source.read_text()
        text = re.sub(
            r"^sqlalchemy\.url\s*=.*$",
            f"sqlalchemy.url = {values['dburl']}",
            text,
            flags=re.MULTILINE,
        )
        return f"{GENERATED}\n" + text
    return f"{GENERATED}\n[alembic]\nscript_location = migrations\nsqlalchemy.url = {values['dburl']}\n"


def build_values(root: Path, args: argparse.Namespace) -> dict[str, str]:
    runtime_dir = Path(env("BISQUE_RUNTIME_DIR", str(root / ".bisque"))).expanduser().resolve()
    config_dir = Path(env("BISQUE_CONFIG_DIR", str(runtime_dir / "config"))).expanduser().resolve()
    data_dir = Path(env("BISQUE_DATA_DIR", str(runtime_dir / "data"))).expanduser().resolve()
    external_dir = (
        Path(env("BISQUE_EXTERNAL_DIR", str(runtime_dir / "external"))).expanduser().resolve()
    )
    public_dir = Path(env("BISQUE_PUBLIC_DIR", str(runtime_dir / "public"))).expanduser().resolve()
    reports_dir = (
        Path(env("BISQUE_REPORTS_DIR", str(runtime_dir / "reports"))).expanduser().resolve()
    )
    staging_dir = (
        Path(env("BISQUE_STAGING_DIR", str(runtime_dir / "staging"))).expanduser().resolve()
    )
    log_dir = Path(env("BISQUE_LOG_DIR", str(runtime_dir / "logs"))).expanduser().resolve()
    run_dir = Path(env("BISQUE_RUN_DIR", str(runtime_dir / "run"))).expanduser().resolve()
    upload_tmp = os.environ.get("BISQUE_UPLOAD_TMP_DIR", "")
    upload_dir = Path(upload_tmp).expanduser().resolve() if upload_tmp else data_dir / "uploads"

    http_host = env("BISQUE_HTTP_HOST", "0.0.0.0")
    http_port = env("BISQUE_HTTP_PORT", "8080")
    public_url = env("BISQUE_PUBLIC_URL", f"http://localhost:{http_port}")
    dburl = validate_dburl(env("BISQUE_DBURL", f"sqlite:///{data_dir / 'bisque.db'}"))
    site_cfg = config_dir / "site.cfg"
    existing_secret = read_existing_value(site_cfg, "beaker.session.secret")
    secret = env("BISQUE_SECRET", existing_secret or uuid.uuid4().hex)
    venv = Path(env("VENV", str(root / ".venv"))).expanduser().resolve()
    python_version = env("PYTHON_VERSION", f"{sys.version_info.major}.{sys.version_info.minor}")
    enable_engine_service = as_bool(env("BISQUE_ENABLE_ENGINE_SERVICE", "true"), True)
    services_enabled = env("BISQUE_SERVICES_ENABLED", "")
    services_disabled = os.environ.get("BISQUE_SERVICES_DISABLED")
    if services_disabled is None:
        services_disabled = "" if enable_engine_service else "engine_service"

    return {
        "root": root.as_posix(),
        "source_dir": (root / "source").resolve().as_posix(),
        "runtime_dir": runtime_dir.as_posix(),
        "config_dir": config_dir.as_posix(),
        "data_dir": data_dir.as_posix(),
        "external_dir": external_dir.as_posix(),
        "public_dir": public_dir.as_posix(),
        "reports_dir": reports_dir.as_posix(),
        "staging_dir": staging_dir.as_posix(),
        "log_dir": log_dir.as_posix(),
        "run_dir": run_dir.as_posix(),
        "upload_dir": upload_dir.as_posix(),
        "http_host": http_host,
        "http_port": http_port,
        "public_url": public_url,
        "services_enabled": services_enabled,
        "services_disabled": services_disabled,
        "dburl": dburl,
        "secret": secret,
        "venv": venv.as_posix(),
        "packages_dir": (venv / "lib" / f"python{python_version}" / "site-packages").as_posix(),
        "defaults_dir": (root / "source" / "config-defaults").resolve().as_posix(),
        "module_dirs": resolve_path_list(
            env("BISQUE_MODULE_DIRS", (root / "source" / "modules").resolve().as_posix()),
            root,
        ),
        "fixture_dir": env(
            "BISQUE_TEST_INPUT_DIR",
            (root / "source" / "bqapi" / "bqapi" / "tests" / "fixtures").resolve().as_posix(),
        ),
        "docker_hub": os.environ.get("BISQUE_DOCKER_HUB", "nail04.ece.ucsb.edu:5000"),
        "docker_backend": env("BISQUE_DOCKER_BACKEND", "docker"),
        "docker_callback_url": env("BISQUE_DOCKER_CALLBACK_URL", ""),
        "docker_argo_workflow_template": env(
            "BISQUE_ARGO_WORKFLOW_TEMPLATE", "bqflow-module-template"
        ),
        "docker_argo_gpu_workflow_template": env(
            "BISQUE_ARGO_GPU_WORKFLOW_TEMPLATE", "bqflow-module-gpu-template"
        ),
        "organization": env("BISQUE_ORGANIZATION", "Your Organization"),
        "title": env("BISQUE_TITLE", "Image Repository"),
        "admin_email": env("BISQUE_ADMIN_EMAIL", "YourEmail@YourOrganization"),
        "js_environment": env("BISQUE_JS_ENVIRONMENT", "development"),
        "debug": "true" if as_bool(env("BISQUE_DEBUG", "true"), True) else "false",
        "smtp_host": env("BISQUE_SMTP_HOST", "localhost"),
        "smtp_port": env("BISQUE_SMTP_PORT", "587"),
        "smtp_user": env("BISQUE_SMTP_USER", ""),
        "smtp_password": env("BISQUE_SMTP_PASSWORD", ""),
        "smtp_tls": env("BISQUE_SMTP_TLS", "true").lower(),
        "smtp_ssl": env("BISQUE_SMTP_SSL", "false").lower(),
        "smtp_timeout": env("BISQUE_SMTP_TIMEOUT", "30"),
        "mail_from": env("BISQUE_MAIL_FROM", "noreply@localhost"),
        "mail_from_name": env("BISQUE_MAIL_FROM_NAME", "Bisque System"),
        "email_verification": env("BISQUE_EMAIL_VERIFICATION_ENABLED", "false").lower(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    values = build_values(root, args)
    config_dir = Path(values["config_dir"])
    defaults_dir = Path(values["defaults_dir"])

    for key in (
        "data_dir",
        "external_dir",
        "public_dir",
        "reports_dir",
        "staging_dir",
        "log_dir",
        "run_dir",
        "upload_dir",
    ):
        Path(values[key]).mkdir(parents=True, exist_ok=True)
    config_dir.mkdir(parents=True, exist_ok=True)

    write_generated(config_dir / "site.cfg", make_site_cfg(values))
    write_generated(config_dir / "runtime-bisque.cfg", make_runtime_cfg(values))
    write_generated(config_dir / "h1_paster.cfg", make_paster_cfg(values))
    write_generated(config_dir / "test.ini", make_test_cfg(values))
    write_generated(config_dir / "alembic.ini", make_alembic_cfg(defaults_dir, values))

    copy_default(defaults_dir, "who.ini", config_dir / "who.ini")
    copy_default(defaults_dir, "registration.cfg", config_dir / "registration.cfg")
    copy_default(defaults_dir, "server.ini", config_dir / "server.ini")
    copy_default(defaults_dir, "shell.ini", config_dir / "shell.ini")
    set_section_value(config_dir / "who.ini", "plugin:auth_tkt", "secret", values["secret"])

    print(f"Generated BisQue config under {config_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
