#!/usr/bin/env python
# script for controlling bisque usually from an init.d script 
# copy this script to somewhere in your accessible path
import os
import sys
import signal
import optparse
import subprocess 

###
if __name__== "__main__":
    parser = optparse.OptionParser()
    parser.add_option('-d', '--dir')
    options, args = parser.parse_args()

    BISQUE_ROOT=options.dir or os.environ.get('BISQUE_ROOT')

    if BISQUE_ROOT is None:
        print >>sys.stderr, 'BISQUE_ROOT not set'
        sys.exit(2)

    if not os.path.isdir(BISQUE_ROOT):
        print >>sys.stderr, 'BISQUE_ROOT not a directory'
        sys.exit(2)

    if len(args) < 1:
        print >>sys.stderr, 'must supply command start|stop'
        sys.exit(2)

    bin = 'Scripts' if os.name =='nt' else 'bin'
    # Activate virtualenv
    #activate = os.path.join(BISQUE_ROOT, 'bqenv', bin, 'activate_this.py')
    #execfile(activate, dict(__file__=activate))

    path = os.environ['PATH']
    path = os.path.join(BISQUE_ROOT, 'bqenv', bin) + os.pathsep + path
    os.putenv ('PATH', path)
    os.environ['PATH'] = path
    
    command = ['.', 'bqenv/bin/activate;', 'bq-admin', 'server', ]
    command.extend (args)
    proc = subprocess.call (' '.join(command), cwd = BISQUE_ROOT, shell=True)

    sys.exit(proc)
        









